# mkdocs.yml
site_name: Data Science
site_author: nnthanh101@gmail.com

theme:
  name: "material"
  custom_dir: docs/overrides

  icon:
    logo: "logo"
  favicon: "images/favicon.ico"

plugins:
  - mkdocstrings

nav:
  - Data Science Overview: index.md
  ## Computer Science 101
  - Python 101:
    - Tutorials: 'python/tutorials.md'
    - How-To Guides: 'python/guides.md'
    - Reference: 'python/reference.md'
    - Explanation: 'python/explanation.md'
  ## TODO: Math for Computer Science
  # - Math for CS:
  #   - Overview: index.md
